"""
One-click setup wizard (bootstrap phase).

When the backend runs with SETUP_MODE=true (the temporary `setup` compose
service), this router:

  - serves the setup page (GET /setup and / → redirect),
  - reports provisioning status (GET /api/setup/status),
  - provisions the deployment (POST /api/setup/provision):

      1. validates the form (company, admin username/password, local IP, and
         the email notification channel),
      2. fills the SMTP host/port/TLS from the chosen provider preset
         (gmail / hotmail / outlook / office365 / hostinger / other) — only
         the mailbox username + password are required from the operator,
      3. upserts infra/.env with the generated values (company, portal IP,
         SMTP, enrollment key, admin username),
      4. writes infra/agent-config.json consumed by the agent installer, and
      5. creates the bootstrap admin account in the shared portal DB.

Once provisioned, `infra/install.sh` (which is polling this endpoint) stops
the setup service, generates HTTPS certs, and brings up the full stack.
"""
from __future__ import annotations

import ipaddress
import json
import secrets
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse

from app import users
from app.config import settings

router = APIRouter(prefix="/api/setup", tags=["setup"])

SETUP_HTML = Path(__file__).resolve().parent.parent / "static" / "setup.html"

# Provider -> SMTP preset. The operator only ever supplies a mailbox address,
# username and password; everything else is derived here.
SMTP_PRESETS: dict[str, dict] = {
    "gmail":     {"host": "smtp.gmail.com",         "port": 465, "tls": "ssl"},
    "hotmail":   {"host": "smtp-mail.outlook.com",  "port": 587, "tls": "starttls"},
    "outlook":   {"host": "smtp-mail.outlook.com",  "port": 587, "tls": "starttls"},
    "office365": {"host": "smtp.office365.com",     "port": 587, "tls": "starttls"},
    "hostinger": {"host": "smtp.hostinger.com",     "port": 465, "tls": "ssl"},
    "other":     {"host": "",                      "port": 587, "tls": "starttls"},
}

_ADMIN_ROLES = ["viewer", "support_engineer", "cleanup_approver"]


def _infra_dir() -> Path:
    if not settings.infra_dir:
        raise HTTPException(500, "INFRA_DIR not mounted — setup wizard cannot write config")
    return Path(settings.infra_dir)


def _env_path() -> Path:
    return _infra_dir() / ".env"


def _provisioned() -> bool:
    return (_infra_dir() / ".provisioned").exists()


def _load_env() -> dict[str, str]:
    env: dict[str, str] = {}
    path = _env_path()
    if path.exists():
        for line in path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            env[key.strip()] = value.strip()
    return env


def _upsert_env(updates: dict[str, str]) -> None:
    """Merge `updates` into infra/.env, preserving comments and other keys."""
    path = _env_path()
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("# Auto-generated by the Aaditech setup wizard.\n")
    lines = path.read_text().splitlines()
    keys = {line.split("=", 1)[0].strip() for line in lines if "=" in line and not line.lstrip().startswith("#")}

    new_lines = []
    for key, value in updates.items():
        if key in keys:
            continue  # existing keys (e.g. generated secrets) are preserved
        new_lines.append(f"{key}={value}")
    if new_lines:
        path.write_text("\n".join([*lines, *new_lines]) + "\n")


def _validate_ip(value: str) -> str:
    value = (value or "").strip()
    try:
        ipaddress.ip_address(value)
    except ValueError:
        raise HTTPException(400, f"'{value}' is not a valid IP address")
    return value


def _validate_payload(payload: dict) -> dict:
    company = (payload.get("company_name") or "").strip()
    username = (payload.get("admin_username") or "").strip()
    password = payload.get("admin_password") or ""
    local_ip = _validate_ip(payload.get("local_ip"))

    if not company:
        raise HTTPException(400, "Company name is required")
    if not username:
        raise HTTPException(400, "Admin username is required")
    if len(password) < 8:
        raise HTTPException(400, "Admin password must be at least 8 characters")

    email = payload.get("email") or {}
    provider = (email.get("provider") or "other").strip().lower()
    if provider not in SMTP_PRESETS:
        raise HTTPException(400, f"Unknown email provider: {provider}")
    email_address = (email.get("address") or "").strip()
    email_username = (email.get("username") or "").strip()
    email_password = email.get("password") or ""

    if email_address and provider != "other" and not (email_username and email_password):
        raise HTTPException(400, "Email username and password are required for the chosen provider")

    return {
        "company_name": company,
        "admin_username": username,
        "admin_password": password,
        "local_ip": local_ip,
        "email": {
            "provider": provider,
            "address": email_address,
            "username": email_username,
            "password": email_password,
        },
    }


@router.get("/status")
async def setup_status():
    if not settings.setup_mode:
        # Normal (provisioned) portal mode — the wizard is considered done.
        return {"configured": True, "company_name": settings.company_name}
    return {
        "configured": _provisioned(),
        "company_name": _load_env().get("COMPANY_NAME", ""),
    }


@router.get("/presets")
async def setup_presets():
    """SMTP presets for the wizard UI (host/port are pre-filled, never leaked)."""
    return {"providers": sorted(SMTP_PRESETS.keys())}


@router.post("/provision")
async def provision(payload: dict):
    if _provisioned():
        return JSONResponse({"configured": True, "message": "Already provisioned"}, status_code=409)

    data = _validate_payload(payload)

    env = _load_env()
    enroll_key = env.get("WAZUH_ENROLL_KEY") or secrets.token_urlsafe(24)

    smtp_preset = SMTP_PRESETS[data["email"]["provider"]]
    env_updates = {
        "COMPANY_NAME": data["company_name"],
        "PORTAL_IP": data["local_ip"],
        "ADMIN_USERNAME": data["admin_username"],
        "WAZUH_ENROLL_KEY": enroll_key,
        "SMTP_HOST": smtp_preset["host"],
        "SMTP_PORT": str(smtp_preset["port"]),
        "SMTP_USERNAME": data["email"]["username"],
        "SMTP_PASSWORD": data["email"]["password"],
        "SMTP_FROM_ADDRESS": data["email"]["address"],
        "SMTP_USE_TLS": smtp_preset["tls"],
    }
    _upsert_env(env_updates)

    # Agent installer config — same values the exe needs at install time
    # (the .exe itself is portable; this is the per-deployment answer file).
    agent_config = {
        "managerIp": data["local_ip"],
        "wazuhAgentVersion": env.get("WAZUH_AGENT_VERSION", "4.14.5"),
        "wazuhEnrollKey": enroll_key,
        "zabbixServerIp": data["local_ip"],
        "zabbixAgentVersion": env.get("ZABBIX_AGENT_VERSION", "7.4.3"),
        "meshCentralUrl": f"https://{data['local_ip']}:4433",
        "meshId": env.get("MESHCENTRAL_MESH_ID", ""),
    }
    (_infra_dir() / "agent-config.json").write_text(json.dumps(agent_config, indent=2))

    # Bootstrap admin account (local login).
    try:
        admin = users.create_user(data["admin_username"], data["admin_password"], list(_ADMIN_ROLES))
    except ValueError as exc:
        raise HTTPException(400, str(exc))

    (_infra_dir() / ".provisioned").write_text(
        json.dumps(
            {"company": data["company_name"], "portal_ip": data["local_ip"], "by": "setup-wizard"},
            indent=2,
        )
    )

    email_channel = data["email"]["address"]
    return {
        "configured": True,
        "company_name": data["company_name"],
        "admin_username": admin["username"],
        "portal_url": f"https://{data['local_ip']}",
        "enrollment_key": enroll_key,
        "email_channel": email_channel or "disabled",
        "smtp": {
            "host": smtp_preset["host"],
            "port": smtp_preset["port"],
            "tls": smtp_preset["tls"],
        },
        "message": (
            "Provisioned. install.sh is finishing the deployment (certs + full "
            f"stack). Sign in at https://{data['local_ip']} with {data['admin_username']}."
        ),
    }
