"""
One-click setup wizard (bootstrap phase).

When the backend runs with SETUP_MODE=true (the temporary `setup` compose
service), this router:

  - serves the setup page (GET /setup and / → redirect),
  - reports provisioning status (GET /api/setup/status),
  - provisions the deployment (POST /api/setup/provision):

      1. validates the form (company, admin username/password, local IP, and
         the optional notification channels: email SMTP, Telegram, MS Teams),
      2. GENERATES EVERY service secret in one shot (Wazuh, Zabbix, GLPI,
         OCS, MeshCentral, Grafana, JWT, agent enrollment key) — before the
         wizard runs infra/.env is deliberately blank,
      3. fills the SMTP host/port/TLS from the chosen provider preset
         (gmail / hotmail / outlook / office365 / hostinger / other) — only
         the mailbox username + password are required from the operator,
      4. upserts infra/.env with everything (company, portal IP, SMTP,
         Telegram/Teams/GitHub PAT, secrets, admin username),
      5. writes infra/agent-config.json consumed by the agent installer, and
      6. creates the bootstrap admin account in the shared portal DB.

Once provisioned, `infra/install.sh` (which is polling this endpoint) stops
the setup service, generates HTTPS certs, and brings up the full stack.
"""
from __future__ import annotations

import ipaddress
import json
import os
import secrets
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse

from app import crypto, provision_secrets, users
from app.config import settings

router = APIRouter(prefix="/api/setup", tags=["setup"])

SETUP_HTML = Path(__file__).resolve().parent.parent / "static" / "setup.html"

# Provider -> SMTP preset. The operator only ever supplies a mailbox address,
# username and password; everything else is derived here.
SMTP_PRESETS: dict[str, dict] = {
    "gmail":     {"host": "smtp.gmail.com",         "port": 465, "tls": "ssl"},
    "hotmail":   {"host": "smtp-mail.outlook.com",  "port": 587, "tls": "starttls"},
    "outlook":   {"host": "smtp-mail.outlook.com",  "port": 587, "tls": "starttls"},
    "office365": {"host": "smtp.office365.com",     "port": 587, "tls": "starttls"},
    "hostinger": {"host": "smtp.hostinger.com",     "port": 465, "tls": "ssl"},
    "other":     {"host": "",                      "port": 587, "tls": "starttls"},
}

_ADMIN_ROLES = ["viewer", "support_engineer", "cleanup_approver"]


def _infra_dir() -> Path:
    if not settings.infra_dir:
        raise HTTPException(500, "INFRA_DIR not mounted — setup wizard cannot write config")
    return Path(settings.infra_dir)


def _env_path() -> Path:
    return _infra_dir() / ".env"


def _provisioned() -> bool:
    return (_infra_dir() / ".provisioned").exists()


def _env_value(value: str) -> str:
    """Serialize a .env value so a '#'/'='/space in it can't corrupt the file.
    Values are double-quoted (and inner quotes escaped) when needed; the
    wizard-generated secrets are URL-safe so they pass through unquoted."""
    value = str(value)
    if any(ch in value for ch in '# ="'):
        escaped = value.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{escaped}"'
    return value


def _load_env() -> dict[str, str]:
    env: dict[str, str] = {}
    path = _env_path()
    if path.exists():
        for line in path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            value = value.strip()
            if value.startswith('"') and value.endswith('"'):
                value = value[1:-1].replace('\\"', '"').replace('\\\\', '\\')
            env[key.strip()] = value
    return env


def _upsert_env(updates: dict[str, str]) -> None:
    """Merge `updates` into infra/.env, preserving comments and other keys.

    Values provided here WIN over what's in the file — the caller decides
    which keys to include (the wizard only passes freshly-generated secrets
    for keys that were blank, so existing secrets are preserved).
    """
    path = _env_path()
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("# Auto-generated by the Aaditech setup wizard.\n")
    lines = path.read_text().splitlines()

    updated_keys = set()
    new_lines = []
    for line in lines:
        stripped = line.lstrip()
        if "=" in line and not stripped.startswith("#"):
            key = line.split("=", 1)[0].strip()
            if key in updates:
                new_lines.append(f"{key}={_env_value(updates[key])}")
                updated_keys.add(key)
                continue
        new_lines.append(line)
    for key, value in updates.items():
        if key not in updated_keys:
            new_lines.append(f"{key}={_env_value(value)}")
    path.write_text("\n".join(new_lines) + "\n")


def _validate_ip(value: str) -> str:
    value = (value or "").strip()
    try:
        ipaddress.ip_address(value)
    except ValueError:
        raise HTTPException(400, f"'{value}' is not a valid IP address")
    return value


def _validate_channels(payload: dict) -> dict:
    """Parse the optional notification channels (email / telegram / teams)
    plus the optional GitHub build PAT. Each is validated independently and
    defaults to "off" when omitted."""
    email = payload.get("email") or {}
    provider = (email.get("provider") or "other").strip().lower()
    if provider not in SMTP_PRESETS:
        raise HTTPException(400, f"Unknown email provider: {provider}")
    email_address = (email.get("address") or "").strip()
    email_username = (email.get("username") or "").strip()
    email_password = email.get("password") or ""

    if email_address and provider != "other" and not (email_username and email_password):
        raise HTTPException(400, "Email username and password are required for the chosen provider")

    telegram = payload.get("telegram") or {}
    bot_token = (telegram.get("bot_token") or "").strip()
    chat_id = (telegram.get("chat_id") or "").strip()
    if bool(bot_token) != bool(chat_id):
        raise HTTPException(400, "Telegram requires BOTH a bot token and a chat ID (or neither)")

    teams = payload.get("teams") or {}
    teams_webhook = (teams.get("webhook_url") or "").strip()
    if teams_webhook and not teams_webhook.startswith("https://"):
        raise HTTPException(400, "MS Teams webhook URL must start with https://")

    github_pat = (payload.get("github_pat") or "").strip()

    return {
        "email": {
            "provider": provider,
            "address": email_address,
            "username": email_username,
            "password": email_password,
        },
        "telegram": {"bot_token": bot_token, "chat_id": chat_id},
        "teams": {"webhook_url": teams_webhook},
        "github_pat": github_pat,
    }


def _validate_payload(payload: dict) -> dict:
    company = (payload.get("company_name") or "").strip()
    username = (payload.get("admin_username") or "").strip()
    password = payload.get("admin_password") or ""
    local_ip = _validate_ip(payload.get("local_ip"))

    if not company:
        raise HTTPException(400, "Company name is required")
    if not username:
        raise HTTPException(400, "Admin username is required")
    if len(password) < 8:
        raise HTTPException(400, "Admin password must be at least 8 characters")

    return {
        "company_name": company,
        "admin_username": username,
        "admin_password": password,
        "local_ip": local_ip,
        "mesh_id": (payload.get("mesh_id") or "").strip(),
        "channels": _validate_channels(payload),
    }


@router.get("/status")
async def setup_status():
    if not settings.setup_mode:
        # Normal (provisioned) portal mode — the wizard is considered done.
        return {"configured": True, "company_name": settings.company_name}
    return {
        "configured": _provisioned(),
        "company_name": _load_env().get("COMPANY_NAME", ""),
        "dependencies": _read_preflight(),
    }


def _read_preflight() -> dict:
    """Surface the host dependency report (from infra/preflight.sh) so the
    wizard can show what's installed vs pending. Empty => no report yet."""
    path = _infra_dir() / ".preflight.json"
    try:
        return json.loads(path.read_text())
    except (OSError, ValueError):
        return {}


@router.get("/presets")
async def setup_presets():
    """SMTP presets for the wizard UI (host/port are pre-filled, never leaked)."""
    return {"providers": sorted(SMTP_PRESETS.keys())}


@router.post("/provision")
async def provision(payload: dict):
    if not settings.setup_mode:
        # Provision only exists on the temporary bootstrap service — in normal
        # portal mode /infra is mounted read-only and writing .env would 500.
        return JSONResponse(
            {"configured": True, "message": "Setup only runs on the bootstrap service"},
            status_code=403,
        )
    if _provisioned():
        return JSONResponse({"configured": True, "message": "Already provisioned"}, status_code=409)

    data = _validate_payload(payload)
    env = _load_env()
    channels = data["channels"]

    # 1) Generate EVERY blank service secret now — infra/.env is blank before
    #    this point, so the entire secret set is created here in one shot.
    #    Keys that were already populated (re-run safety, manual setup.sh)
    #    are preserved.
    env_updates: dict[str, str] = {}
    for key in provision_secrets.SECRET_KEYS:
        if not env.get(key):
            env_updates[key] = secrets.token_urlsafe(32)

    # 2) Wizard-collected values.
    smtp_preset = SMTP_PRESETS[channels["email"]["provider"]]
    env_updates.update({
        "COMPANY_NAME": data["company_name"],
        "PORTAL_IP": data["local_ip"],
        "ADMIN_USERNAME": data["admin_username"],
        # Wazuh API service account — fixed username, random password above.
        "WAZUH_API_USER": env.get("WAZUH_API_USER") or "aaditech-portal-svc",
        "SMTP_HOST": smtp_preset["host"],
        "SMTP_PORT": str(smtp_preset["port"]),
        "SMTP_USERNAME": channels["email"]["username"],
        "SMTP_PASSWORD": channels["email"]["password"],
        "SMTP_FROM_ADDRESS": channels["email"]["address"],
        "SMTP_USE_TLS": smtp_preset["tls"],
        "TELEGRAM_BOT_TOKEN": channels["telegram"]["bot_token"],
        "TELEGRAM_CHAT_ID": channels["telegram"]["chat_id"],
        "TEAMS_WEBHOOK_URL": channels["teams"]["webhook_url"],
        "GITHUB_BUILD_PAT": channels["github_pat"],
        "GITHUB_REPO": env.get("GITHUB_REPO") or "j9619655391-max/Aaditech",
    })
    # Optional MeshCentral device-group ID (from the MeshCentral admin UI —
    # only becomes meaningful once a device group exists). Preserved if the
    # operator already set it in infra/.env.
    if (data.get("mesh_id") or "").strip():
        env_updates["MESHCENTRAL_MESH_ID"] = data["mesh_id"].strip()
    elif env.get("MESHCENTRAL_MESH_ID"):
        env_updates["MESHCENTRAL_MESH_ID"] = env["MESHCENTRAL_MESH_ID"]
    _upsert_env(env_updates)

    # Refresh enrollment key from the (now complete) env.
    enroll_key = env.get("WAZUH_ENROLL_KEY") or env_updates.get("WAZUH_ENROLL_KEY") or ""

    # Agent installer config — same values the exe needs at install time
    # (the .exe itself is portable; this is the per-deployment answer file).
    # Encrypted AT REST with AGENT_CONFIG_KEY — the plaintext only exists in
    # the process and over HTTPS via the /api/agent-installer endpoints
    # (app/crypto.py). setup.py runs in the setup service; downloads.py runs in
    # the main portal-backend, both read the same infra/.env key.
    agent_config = {
        "managerIp": data["local_ip"],
        "wazuhAgentVersion": env.get("WAZUH_AGENT_VERSION", "4.9.0"),
        "wazuhEnrollKey": enroll_key,
        "zabbixServerIp": data["local_ip"],
        "zabbixAgentVersion": env.get("ZABBIX_AGENT_VERSION", "6.4.20"),
        "meshCentralUrl": f"https://{data['local_ip']}:4433",
        "meshId": env.get("MESHCENTRAL_MESH_ID") or env_updates.get("MESHCENTRAL_MESH_ID", ""),
    }
    _infra_agent_config = _infra_dir() / "agent-config.json"
    _infra_agent_config.write_text(
        crypto.encrypt_json(agent_config, env.get("AGENT_CONFIG_KEY") or env_updates.get("AGENT_CONFIG_KEY", ""))
    )
    os.chmod(_infra_agent_config, 0o600)

    # Bootstrap admin account (local login).
    try:
        admin = users.create_user(data["admin_username"], data["admin_password"], list(_ADMIN_ROLES))
    except ValueError as exc:
        raise HTTPException(400, str(exc))

    (_infra_dir() / ".provisioned").write_text(
        json.dumps(
            {"company": data["company_name"], "portal_ip": data["local_ip"], "by": "setup-wizard"},
            indent=2,
        )
    )

    email_channel = channels["email"]["address"]
    return {
        "configured": True,
        "company_name": data["company_name"],
        "admin_username": admin["username"],
        "portal_url": f"https://{data['local_ip']}",
        "enrollment_key": enroll_key,
        "email_channel": email_channel or "disabled",
        "telegram_channel": bool(channels["telegram"]["bot_token"]),
        "teams_channel": bool(channels["teams"]["webhook_url"]),
        "secrets_generated": len(env_updates),
        "smtp": {
            "host": smtp_preset["host"],
            "port": smtp_preset["port"],
            "tls": smtp_preset["tls"],
        },
        "message": (
            "Provisioned. install.sh is finishing the deployment (certs + full "
            f"stack). Sign in at https://{data['local_ip']} with {data['admin_username']}."
        ),
    }
