"""
Secret at-rest encryption for the Aaditech Portal.

Files like `infra/agent-config.json` contain live credentials (the Wazuh
enrollment key, service tokens). They are encrypted on disk with AES-128-GCM
via Fernet (the `cryptography` package) using a key stored in `infra/.env`
(`AGENT_CONFIG_KEY`, generated by the setup wizard). The plaintext only ever
exists:

  - inside the backend process while encrypting/decrypting,
  - over the wire, via the portal's HTTPS endpoints (transport encryption).

Nothing on disk holds secrets in plaintext.
"""
from __future__ import annotations

import base64
import hashlib

from cryptography.fernet import Fernet, InvalidToken


def _key(secret: str) -> Fernet:
    """Derive a stable Fernet key from any env secret string."""
    digest = hashlib.sha256(secret.encode("utf-8")).digest()
    return Fernet(base64.urlsafe_b64encode(digest))


def encrypt_json(payload: dict, secret: str) -> str:
    """Serialize + encrypt a dict to a Fernet token (base64 str)."""
    import json

    if not secret:
        raise ValueError("AGENT_CONFIG_KEY is empty — cannot encrypt at rest")
    return _key(secret).encrypt(json.dumps(payload).encode("utf-8")).decode("ascii")


def decrypt_json(token: str, secret: str) -> dict:
    """Decrypt a Fernet token written by encrypt_json()."""
    import json

    if not secret:
        raise ValueError("AGENT_CONFIG_KEY is empty — cannot decrypt")
    try:
        return json.loads(_key(secret).decrypt(token.encode("ascii")))
    except InvalidToken as exc:
        raise ValueError("agent-config.json is corrupted or the key changed") from exc
