"""
One source of truth for every random secret the platform needs.

Before the one-click setup wizard runs, infra/.env is intentionally BLANK (no
secrets exist anywhere). On wizard submit, `generate_all_secrets()` creates
the full secret set in one shot — Wazuh, Zabbix, GLPI, OCS, MeshCentral,
Grafana, the portal JWT secret and the Wazuh agent enrollment key — and the
wizard writes them into infra/.env. Nothing exists before setup; everything
exists after it.

Keep this list in sync with `infra/generate-secrets.sh` (the manual path used
by setup.sh). Both must produce the same keys.
"""
from __future__ import annotations

import secrets

# Platform service secrets, all random. Keys are infra/.env variable names.
# Wizard-submitted values (SMTP, company, admin, GitHub PAT, notification
# channels) are handled separately in app/routers/setup.py.
SECRET_KEYS: list[str] = [
    # Wazuh
    "WAZUH_API_PASSWORD",
    # Zabbix
    "ZABBIX_DB_PASSWORD",
    "ZABBIX_API_TOKEN",
    # GLPI
    "GLPI_DB_ROOT_PASSWORD",
    "GLPI_DB_PASSWORD",
    "GLPI_APP_TOKEN",
    "GLPI_USER_TOKEN",
    # OCS Inventory
    "OCS_DB_ROOT_PASSWORD",
    "OCS_DB_PASSWORD",
    # MeshCentral
    "MESHCENTRAL_API_KEY",
    # Grafana
    "GRAFANA_ADMIN_PASSWORD",
    "GRAFANA_SERVICE_TOKEN",
    # Portal
    "JWT_SECRET",
    # Agent enrollment
    "WAZUH_ENROLL_KEY",
    # Agent config at-rest encryption (Fernet key seed for infra/agent-config.json)
    "AGENT_CONFIG_KEY",
]

# Fixed (non-random) values that must exist in .env so the compose stack and
# backend resolve. Blank secrets are forbidden in production — the wizard
# fills everything.
NON_SECRET_KEYS: list[str] = [
    "WAZUH_API_USER",
    "COMPANY_NAME",
    "PORTAL_IP",
    "SMTP_HOST",
    "SMTP_PORT",
    "SMTP_USERNAME",
    "SMTP_PASSWORD",
    "SMTP_FROM_ADDRESS",
    "SMTP_USE_TLS",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
    "SLACK_WEBHOOK_URL",
    "TEAMS_WEBHOOK_URL",
    "AZURE_CLIENT_ID",
    "AZURE_CLIENT_SECRET",
    "AZURE_TENANT_ID",
    "AZURE_ADMIN_GROUP_IDS",
    "QUARANTINE_NETWORK_SHARE",
    "GITHUB_BUILD_PAT",
    "GITHUB_REPO",
    # MeshCentral device-group ID (assigned by the MeshCentral admin UI once
    # a device group exists — operator-provided, cannot be auto-generated).
    "MESHCENTRAL_MESH_ID",
]


def _random() -> str:
    return secrets.token_urlsafe(32)


def generate_all_secrets() -> dict[str, str]:
    """Fresh random values for every secret the stack needs."""
    return {key: _random() for key in SECRET_KEYS}


def blank_env() -> str:
    """The template install.sh writes BEFORE the wizard runs — every key
    present, no secrets populated. Nothing is secret before setup. (SMTP_PORT
    defaults to 587 because the backend parses it as an int even when the
    SMTP channel is off; the wizard overwrites it with the provider port.)"""
    lines = [
        "# Auto-generated by install.sh — BLANK until the setup wizard runs.",
        "# The wizard generates all service tokens on submit. Do not commit this file.",
        "",
    ]
    for key in SECRET_KEYS + NON_SECRET_KEYS:
        value = "587" if key == "SMTP_PORT" else ""
        lines.append(f"{key}={value}")
    lines.append("WAZUH_AGENT_VERSION=4.9.0")
    lines.append("ZABBIX_AGENT_VERSION=6.4.20")
    lines.append("")
    return "\n".join(lines)
